version: '{build}'

environment:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

build_script:
  - npm install
  - npm pack --silent

artifacts:
  - path: '*.tgz'

test_script:
  # Check that we are able to install our package.
  - bash -c "npm install -g *.tgz"
  # Check that we are able to build an app.
  - npm install fuse-sdk -g
  - uno build android app
